### ISSUE TITLE
None of the tutorial examples apart from `sync_example` works

### ISSUE THREAD

**Issue by molleweide** [ms-jpq/neovim-async-tutorial#7]
Hi there,

I have read through the tutorial and tried to understand the code.
When calling each example, the only one that actually prints anything is the `sync_example`.

**Comment by dewoller** [comment]
Hi @molleweide .  I puzzled over that same question for the past few days, and just this noticed this morning that @ms-jpq calls the functions (other than sync_example) with another set of brackets, e.g. ``` async_example()() ``` . This works!  Thanks @ms-jpq for the lovely clean code, and good tutorial.  Next time I will remember to actually *read the instructions*!

Until next time

**Comment by molleweide** [comment]
> Hi @molleweide . I puzzled over that same question for the past few days, and just this noticed this morning that @ms-jpq calls the functions (other than sync_example) with another set of brackets, e.g. `async_example()()` . This works! Thanks @ms-jpq for the lovely clean code, and good tutorial. Next time I will remember to actually _read the instructions_!
> 
> Until next time

Aaaah, now when you told me this I looked into the `plugins/` file and I can see the double ()() too so thanks a lot for telling me about this.

I agree, this tutorial was a true eye opener for me too!
